### ISSUE TITLE
Support SELECT ... WHERE .. without FROM

### ISSUE THREAD

**Issue by dyzsr** [pingcap/parser#1111] opened 2020-12-01 10:24 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB

``` mysql
mysql root@127.0.0.1:test> select 1 where 1 group by 1 having 1 order by 1
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 14 near "where 1 group by 1 having 1 order by 1" ')
```

MySQL

``` mysql
mysql root@localhost:test> select 1 where 1 group by 1 having 1 order by 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set
Time: 0.008s
```

**Describe the feature you'd like:**

Support it like MySQL.

**Describe alternatives you've considered:**

Support

```mysql
select 1 from dual where 1 group by 1 having 1 order by 1
```

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kennytm** [comment] 2020-12-02 06:51
thanks, but this is a duplicate of #115.

**Closed by kennytm** 2020-12-02 06:51 UTC
