### ISSUE TITLE
Fix TiDB behavior: constraint check

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#601] opened 2019-10-31 12:15 UTC
Index issue: #598 

### SQL example
```sql
CREATE TABLE t (a INT CHECK (a > 1));
ALTER TABLE t ADD CONSTRAINT crn CHECK (a > 1);
ALTER TABLE t ALTER CHECK
```

### Current implementation
`ColumnOptionCheck`, `ConstraintType.ConstraintCheck`, `AlterTableAlterCheck`, and `AlterTableDropCheck` are ignored by TiDB.

### Expected implementation
Throw a warning.

**Comment by chanme** [comment] 2020-06-06 08:49
@tangenta , I'm trying to solve this issue as a new contributor. where should I throw a warning, in pingcap/parser or pingcap/tidb? (I think it should be fixed in pingcap/tidb, but the issue is under pingcap/parser, a bit confused)

**Comment by tangenta** [comment] 2020-06-06 08:52
@chanme It should be fixed in pingcap/tidb :)

**Comment by chanme** [comment] 2020-06-06 15:43
I have almost finished solving this issue, during writing the unit tests, I find out that some warnings are already generated by the pingcap/parser repo, should I first make a PR to remove the warning in the parser then add warning in pingcap/tidb to solve this issue?

Original Warning is:
| Warning | 1064 | You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 36 near ")"The CHECK clause is parsed but ignored by all storage engines.

**Closed** 2020-07-02 05:28 UTC
Labels: for new contributors
